version: "3.6"
services:
  api:
    container_name: api
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/root
    healthcheck:
      disable: true
    restart: unless-stopped
    ports:
      - 3001:3001
    tty: true
  db:
    image: mongo:latest
    ports:
      - 27017:27017
